226-passkey_demo/passkeys/urls.py
from django.urls import path
from . import FIDO2,views

app_name = 'passkeys'
urlpatterns = [
    path('auth/begin',FIDO2.auth_begin, name='auth_begin'),
    path('auth/complete',FIDO2.auth_complete, name='auth_complete'),
    path('reg/begin',FIDO2.reg_begin,name = 'reg_begin'),
    path('reg/complete',FIDO2.reg_complete,name = 'reg_complete'),
    path('',views.index, name='home'),
    path('enroll/',views.index, name='enroll',kwargs={'enroll':True}),


    path('del/',views.delKey, name='delKey'),
    path('toggle/',views.toggleKey, name='toggle'),
    ]

226-passkey_demo/passkeys/models.py
from django.contrib.auth import get_user_model
from django.db import models


class UserPasskey(models.Model):
    user_model = get_user_model()
    user = models.ForeignKey(user_model,on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    enabled= models.BooleanField(default=True)
    platform = models.CharField(max_length=255,default='')
    added_on = models.DateTimeField(auto_now_add=True)
    last_used = models.DateTimeField(null=True,default=None)
    credential_id = models.CharField(max_length=255, unique=True)
    token = models.CharField(max_length=255, null=False)

226-passkey_demo/passkeys/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render

from .models import UserPasskey

@login_required
def index(request,enroll=False): # noqa
    keys = UserPasskey.objects.filter(user=request.user) # pragma: no cover
    return render(request,'PassKeys.html',{"keys":keys,"enroll":enroll}) # pragma: no cover


@login_required
def delKey(request):
    key=UserPasskey.objects.get(id=request.GET["id"])
    if key.user.pk  == request.user.pk:
        key.delete()
        return HttpResponse("Deleted Successfully")
    return HttpResponse("Error: You own this token so you can't delete it", status=403)

@login_required
def toggleKey(request):
    id=request.GET["id"]
    q=UserPasskey.objects.filter(user=request.user, id=id)
    if q.count()==1:
        key=q[0]
        key.enabled=not key.enabled
        key.save()
        return HttpResponse("OK")
    return HttpResponse("Error: You own this token so you can't toggle it", status=403)

226-passkey_demo/passkeys/templates/PassKeys.html
{% extends "PassKeys_base.html" %}
{% load static %}

{% block extrahead %}
{{block.super}}
    <script type='text/javascript' src="{% static 'admin/js/vendor/jquery/jquery.min.js' %}"></script>

    <script type="application/javascript" src="{% static 'passkeys/js/base64url.js'%}"></script>
    <script type="application/javascript" src="{% static 'passkeys/js/helpers.js'%}"></script>
    <script type="application/javascript">
    var MakeCredReq = (makeCredReq) => {
            makeCredReq.publicKey.challenge = base64url.decode(makeCredReq.publicKey.challenge);
            makeCredReq.publicKey.user.id   = base64url.decode(makeCredReq.publicKey.user.id);

            for(let excludeCred of makeCredReq.publicKey.excludeCredentials) {
                excludeCred.id = base64url.decode(excludeCred.id);
            }

            return makeCredReq
        }
    function begin_reg(){
    fetch('{% url 'passkeys:reg_begin' %}',{}).then(function(response) {
      if(response.ok)
      {
          return response.json().then(function (req){
              return MakeCredReq(req)
          });
      }
      throw new Error('Error getting registration data!');
    }).then(function(options) {

        //options.publicKey.attestation="direct"
        console.log(options)

      return navigator.credentials.create(options);
    }).then(function(attestation) {
        attestation["key_name"] = $("#key_name").val();
      return fetch('{% url 'passkeys:reg_complete' %}', {
        method: 'POST',
        body: JSON.stringify(publicKeyCredentialToJSON(attestation))
      });
    }).then(function(response) {

        var stat = response.ok ? 'successful' : 'unsuccessful';
        return response.json()
    }).then(function (res)
        {
      if (res["status"] =='OK')
        $("#res").html("<div class='alert alert-success'>Registered Successfully, <a href='{% url "passkeys:home"%}'> Refresh</a></div>")
      else
        $("#res").html("<div class='alert alert-danger'>Registration Failed as " + res["message"] + ", <a href='javascript:void(0)' onclick='begin_reg()'> try again </a> </div>")


    }, function(reason) {
       $("#res").html("<div class='alert alert-danger'>Registration Failed as " +reason +", <a href='javascript:void(0)' onclick='begin_reg()'> try again </a> </div>")
    })
    }




    function confirmDel(id) {
        $.ajax({
            url:"{% url 'passkeys:delKey' %}",
            data:{"id":id},
            success:function (data) {
                alert(data)
                window.location= "{%url 'passkeys:home'%}";
            }
        })
    }

    function start(){
        $("#modal-title").html("Enter a token name")
        $("#modal-body").html(`<p>Please enter a name for your new token</p>
                                <input type="text" placeholder="e.g Laptop, PC" id="key_name" class="form-control"/><br/>
                                <div id="res"></div>
                                `)
        $("#actionBtn").remove();
        $("#modal-footer").prepend(`<button id='actionBtn' class='btn btn-success' onclick="begin_reg()">Start</button>`)
        $("#popUpModal").modal('show')
    }
    function deleteKey(id,name)
    {
        $("#modal-title").html("Confirm Delete")
        $("#modal-body").html("Are you sure you want to delete '"+name+"'? you may lose access to your system if this your only 2FA.");
        $("#actionBtn").remove()
        $("#modal-footer").prepend("<button id='actionBtn' class='btn btn-danger' onclick='confirmDel("+id+")'>Confirm Deletion</button>")
        $("#popUpModal").modal('show')
    }

    function toggleKey(id) {
        $.ajax({
            url:"{% url 'passkeys:toggle' %}?id="+id,
            success:function (data) {
                if (data == "Error")
                    $("#toggle_"+id).toggle()

            },
            error:function (data) {
                $("#toggle_"+id).toggle()
            }
        })
    }
    {%if enroll%}
        $(document).ready(start)
    {%endif%}

    </script>
    <link href="{% static  'passkeys/css/bootstrap-toggle.min.css' %}" rel="stylesheet">
    <script src="{% static 'passkeys/js/bootstrap-toggle.min.js'%}"></script>
{% endblock %}
{% block content %}
{{block.super}}
    <br/>
    <br/>
    <div class="container">
        <div class="row">
            <div class="offset-5 col-2" style="text-align: center">
                <div class="btn-group">
                    <button class="btn btn-success" onclick='start()'> Add Key</button>
                </div>
            </div>
        </div>
        <br/>
       <table class="table table-striped">
           <tr>
               <th>Name</th>
               <th>Date Added</th>
               <th>Platform</th>
               <th>Last Used</th>
               <th>Status</th>
               <th>Delete</th>
           </tr>
            {% if keys %}
                {% for key in keys %}
                <tr>

                    <td>{{ key.name }}</td>
                    <td>{{ key.added_on }}</td>
                    <td>{{ key.platform }}</td>
                    <td>{% if key.last_used %}{{ key.last_used }}{% else %}Never{% endif %}</td>
                    <td><input type="checkbox" id="toggle_{{ key.id }}" {% if key.enabled %}checked{% endif %} data-onstyle="success" data-offstyle="danger"  onchange="toggleKey({{ key.id }})" data-toggle="toggle" class="status_chk"></td>
                    <td><a href="javascript:void(0)" onclick="deleteKey({{ key.id }},'{{ key.key_type }}')"> <span class="fa fa-trash fa-solid fa-trash-can bi bi-trash-fill"></span></a></td>
                </tr>
                {% endfor %}
            {% else %}
            <tr>
                <td colspan="7" align="center">You didn't have any keys yet.</td>
            </tr>
        {% endif %}
        </table>
    </div>
    {% include "modal.html" %}
{% endblock %}

226-passkey_demo/passkeys/templates/PassKeys_base.html
{% extends "admin/base_site.html" %}
{% block extrahead %}
{{ block.super }}
{% endblock %}
{% block content %}
{{ block.super }}
{% endblock %}

226-passkey_demo/passkeys/templates/modal.html
<div class="modal " tabindex="-1" role="dialog" id="popUpModal" style=" top: 40px;">
  <div class="modal-dialog" style="height: 80%;width: 80%;">
    <div class="modal-content" >
      <div class="modal-header">
        <h4 class="modal-title" id="modal-title"></h4>
          <button type="button" class="close" data-dismiss="modal" data-bs-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body" id="modal-body" >


          </div>
      <div class="modal-footer" id="modal-footer">
        <button type="button" class="btn btn-default btn-secondary" id='btnModalClose' data-dismiss="modal" data-bs-dismiss="modal">Close</button>
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->