230-django_htmx_demo/example/urls.py
from __future__ import annotations

from django.urls import path

from example import views

urlpatterns = [
    path("", views.index),
    path("favicon.ico", views.favicon),
    path("csrf-demo/", views.csrf_demo),
    path("csrf-demo/checker/", views.csrf_demo_checker),
    path("error-demo/", views.error_demo),
    path("error-demo/trigger/", views.error_demo_trigger),
    path("middleware-tester/", views.middleware_tester),
    path("middleware-tester/table/", views.middleware_tester_table),
    path("partial-rendering/", views.partial_rendering),
]

230-django_htmx_demo/example/forms.py
from __future__ import annotations

from django import forms


class OddNumberForm(forms.Form):
    number = forms.IntegerField()

230-django_htmx_demo/example/views.py
from __future__ import annotations

import time
from dataclasses import dataclass

from django.core.paginator import Paginator
from django.http import HttpRequest
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.http import require_GET
from django.views.decorators.http import require_http_methods
from django.views.decorators.http import require_POST
from faker import Faker

from django_htmx.middleware import HtmxDetails
from example.forms import OddNumberForm


# Typing pattern recommended by django-stubs:
# https://github.com/typeddjango/django-stubs#how-can-i-create-a-httprequest-thats-guaranteed-to-have-an-authenticated-user
class HtmxHttpRequest(HttpRequest):
    htmx: HtmxDetails


@require_GET
def index(request: HtmxHttpRequest) -> HttpResponse:
    return render(request, "index.html")


@require_GET
def favicon(request: HtmxHttpRequest) -> HttpResponse:
    return HttpResponse(
        (
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">'
            + '<text y=".9em" font-size="90">🦊</text>'
            + "</svg>"
        ),
        content_type="image/svg+xml",
    )


# CSRF Demo


@require_GET
def csrf_demo(request: HtmxHttpRequest) -> HttpResponse:
    return render(request, "csrf-demo.html")


@require_POST
def csrf_demo_checker(request: HtmxHttpRequest) -> HttpResponse:
    form = OddNumberForm(request.POST)
    if form.is_valid():
        number = form.cleaned_data["number"]
        number_is_odd = number % 2 == 1
    else:
        number_is_odd = False
    return render(
        request,
        "csrf-demo-checker.html",
        {"form": form, "number_is_odd": number_is_odd},
    )


# Error demo


@require_GET
def error_demo(request: HtmxHttpRequest) -> HttpResponse:
    return render(request, "error-demo.html")


@require_GET
def error_demo_trigger(request: HtmxHttpRequest) -> HttpResponse:
    1 / 0
    return render(request, "error-demo.html")  # unreachable


# Middleware tester

# This uses two views - one to render the form, and the second to render the
# table of attributes.


@require_GET
def middleware_tester(request: HtmxHttpRequest) -> HttpResponse:
    return render(request, "middleware-tester.html")


@require_http_methods(["DELETE", "POST", "PUT"])
def middleware_tester_table(request: HtmxHttpRequest) -> HttpResponse:
    return render(
        request,
        "middleware-tester-table.html",
        {"timestamp": time.time()},
    )


# Partial rendering example


# This dataclass acts as a stand-in for a database model - the example app
# avoids having a database for simplicity.


@dataclass
class Person:
    id: int
    name: str


faker = Faker()
people = [Person(id=i, name=faker.name()) for i in range(1, 235)]


@require_GET
def partial_rendering(request: HtmxHttpRequest) -> HttpResponse:
    # Standard Django pagination
    page_num = request.GET.get("page", "1")
    page = Paginator(object_list=people, per_page=10).get_page(page_num)

    # The htmx magic - use a different, minimal base template for htmx
    # requests, allowing us to skip rendering the unchanging parts of the
    # template.
    if request.htmx:
        base_template = "_partial.html"
    else:
        base_template = "_base.html"

    return render(
        request,
        "partial-rendering.html",
        {
            "base_template": base_template,
            "page": page,
        },
    )

230-django_htmx_demo/example/templates/_base.html
{% load django_htmx %}
{% load static %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>django-htmx example app</title>
  <link rel="stylesheet" href="{% static 'mvp.css' %}">

  <!-- An example of how we can configure htmx -->
  <!-- https://htmx.org/docs/#config -->
  <meta name="htmx-config" content='{"historyCacheSize": 15}'>

  <script src="{% static 'htmx.js' %}" defer></script>
  <script src="{% static 'ext/debug.js' %}" defer></script>
  <script src="{% static 'ext/event-header.js' %}" defer></script>
</head>

<!--
  Enable htmx extensions for all requests:
  * debug: https://htmx.org/extensions/debug/
  * event-header: https://htmx.org/extensions/event-header/
-->
<body hx-ext="debug, event-header">
  <header>
    <nav>
      <h1>
        <a href="/">
          django-htmx example app
        </a>
      </h1>
      <ul>
        <li>
          <a href="/csrf-demo/">CSRF Demo</a>
        </li>
        <li>
          <a href="/error-demo/">Error Demo</a>
        </li>
        <li>
          <a href="/middleware-tester/">Middleware Tester</a>
        </li>
        <li>
          <a href="/partial-rendering/">Partial Rendering</a>
        </li>
      </ul>
    </nav>
  </header>
  <main id="main">
    {% block main %}{% endblock %}
  </main>
  <footer>
    <hr>
    <p>
      For more information see <a href="https://github.com/adamchainz/django-htmx">django-htmx</a> and <a href="https://htmx.org/">htmx</a>.
    </p>
  </footer>
  {% django_htmx_script %}
</body>
</html>

230-django_htmx_demo/example/templates/_partial.html
<main id="main">
  {% block main %}{% endblock %}
</main>

230-django_htmx_demo/example/templates/csrf-demo-checker.html
{% if not form.is_valid %}
  Please enter a number
{% elif number_is_odd %}
  {{ form.number.value }} is odd!
{% else %}
  {{ form.number.value }} is not odd.
{% endif %}

230-django_htmx_demo/example/templates/csrf-demo.html
{% extends "_base.html" %}

{% block main %}
  <section>
    <p>
      This form shows you how to implement CSRF with htmx, using <a href="https://dev.htmx.org/attributes/hx-headers/"> the <code>hx-headers</code> attribute</a>.
    </p>
  </section>
  <section>
    <!--
      Note you can place the hx-headers attribute on your <body> tag so it
      affects all requests, reducing repetition.

      The header name may be changed with the CSRF_HEADER_NAME setting;
      https://docs.djangoproject.com/en/stable/ref/settings/#std:setting-CSRF_HEADER_NAME

      Note we use {{ csrf_token }} instead of {% csrf_token %} to get the
      variable rather than a rendered HTML <input>.
    -->
    <form hx-post="/csrf-demo/checker/"
          hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
          hx-target="#result">
      <label for="id_number">
        Number:
      </label>
      <input id="id_number"
             name="number"
             type="text"
             placeholder="">
      <button type="submit">
        Check if odd
      </button>
    </form>
  </section>
  <section>
    <p id="result"><em>Awaiting interaction...</em></p>
  </section>
{% endblock %}

230-django_htmx_demo/example/templates/error-demo.html
{% extends "_base.html" %}

{% block main %}
  <section>
    <p>
      This page shows you django-htmx’s error handler.
    </p>
  </section>
  <section>
    <p>
      {% if DEBUG %}
        The error handler will work, since <code>DEBUG = True</code>.
      {% else %}
        The error handler will <strong>not</strong> work, since <strong>DEBUG = False</strong>.
      {% endif %}
    </p>
  </section>
  <section>
    <button hx-get="/error-demo/trigger/">
      Try divide by zero
    </button>
  </section>
  <section>
    <button hx-get="/bermuda-triangle/">
      Fetch non-existent page
    </button>
  </section>
{% endblock %}

230-django_htmx_demo/example/templates/index.html
{% extends "_base.html" %}

{% block main %}
  <section>
    Welcome to the example app.
    Use one of the links in the navigation to explore!
  </section>
{% endblock %}

230-django_htmx_demo/example/templates/middleware-tester-table.html
{% load example_tags %}

<table id="attribute-test">
  <thead>
    <tr>
      <th>Attribute</th>
      <th>Value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Timestamp</td>
      <td>{{ timestamp }}</td>
    </tr>
    <tr>
      <td><code>request.method</code></td>
      <td><code>{{ request.method|stringformat:'r' }}</code></td>
    </tr>
    <tr>
      <td><code>bool(request.htmx)</code></td>
      <td>
        {% if request.htmx %}
          <code>True</code>
        {% else %}
          <code>For</code>
        {% endif %}
      </td>
    </tr>
    <tr>
      <td><code>request.htmx.boosted</code></td>
      <td><code>{{ request.htmx.boosted|stringformat:'r' }}</code></td>
    </tr>
    <tr>
      <td><code>request.htmx.current_url</code></td>
      <td><code>{{ request.htmx.current_url|stringformat:'r' }}</code></td>
    </tr>
    <tr>
      <td><code>request.htmx.current_url_abs_path</code></td>
      <td><code>{{ request.htmx.current_url_abs_path|stringformat:'r' }}</code></td>
    </tr>
    <tr>
      <td><code>request.htmx.prompt</code></td>
      <td><code>{{ request.htmx.prompt|stringformat:'r' }}</code></td>
    </tr>
    <tr>
      <td><code>request.htmx.target</code></td>
      <td><code>{{ request.htmx.target|stringformat:'r' }}</code></td>
    </tr>
    <tr>
      <td><code>request.htmx.trigger</code></td>
      <td><code>{{ request.htmx.trigger|stringformat:'r' }}</code></td>
    </tr>
    <tr>
      <td><code>request.htmx.trigger_name</code></td>
      <td><code>{{ request.htmx.trigger_name|stringformat:'r' }}</code></td>
    </tr>
    <tr>
      <td>
        <code>request.htmx.triggering_event</code> <br>
        <small>(via <a href="https://htmx.org/extensions/event-header/">event-header extension</a>)</small>
      </td>
      <td>
        {% if request.htmx.triggering_event %}
          <details>
            <summary>JSON</summary>
            <pre style="text-align: left"><code>{{ request.htmx.triggering_event|json_dumps }}</code></pre>
          </details>
        {% else %}
          <code>{{ request.htmx.triggering_event|stringformat:'r' }}</code>
        {% endif %}
      </td>
    </tr>
    <tr>
      <td><code>request.POST.get('keyup_input')</code></td>
      <td><code>{{ request.POST.keyup_input|stringformat:'r' }}</code></td>
    </tr>
  </tbody>
</table>

230-django_htmx_demo/example/templates/middleware-tester.html
{% extends "_base.html" %}

{% block main %}
  <section>
    <!--
      This form itself is never submitted, but acts as a container for the form
      control elements, which make their own individual requests. Since the
      form controls all have the same CSRF header, target, and swap method, we
      define those attributes here and the controls inherit them.
    -->
    <form action="#"
          hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
          hx-target="#attribute-test"
          hx-swap="outerHTML">
      <p>
        The below form controls implement different patterns with HTMX.
        Interact with them to trigger requests that will render a table showing the Django request attributes added and changed by <code>HtmxMiddleware</code>.
      </p>
      <p>
        <button id="basic-button"
                hx-put="/middleware-tester/table/">
          Basic button
        </button>
      </p>
      <p>
        <button id="prompt-button"
                hx-delete="/middleware-tester/table/"
                hx-prompt="What is your answer?">
          Prompt button
        </button>
      </p>
      <p>
        <input id="keyup-input"
               name="keyup_input"
               type="text"
               placeholder="Type something..."
               autocomplete="off"
               hx-post="/middleware-tester/table/"
               hx-trigger="keyup changed delay:100ms"></input>
      </p>
    </form>
  </section>
  <hr>
  <section>
    <p id="attribute-test"><em>Awaiting interaction...</em></p>
  </section>
{% endblock %}

230-django_htmx_demo/example/templates/partial-rendering.html
{% extends base_template %}

{% block main %}
  <section>
    <p>
      This example shows you how you can do partial rendering for htmx requests.
      The view uses an alternative base template for requests made with htmx.
      This base template only renders the <code>&lt;main&gt;</code> element, saving time and bandwidth.
      Paginate through the below list of randomly generated people to see this in action, and study the view and template.
    </p>
    <p><a href="https://django-htmx.readthedocs.io/en/latest/tips.html#partial-rendering">See more in the docs</a>.</p>
  </section>

  <section>
    <table>
      <thead>
        <tr>
          <th>id</th>
          <th>name</th>
        </tr>
      </thead>
      <tbody>
        {% for person in page.object_list %}
          <tr>
            <td>{{ person.id }}</td>
            <td>{{ person.name }}</td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="2">
              No people on this page.
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </section>

  <section>
    <!--
      The htmx attributes set on the nav here are inherited by the child links.
      hx-target tells where htmx to swap the fetched content in, and hx-swap
      tells it how to swap it - by replacing the 'outerHTML' attribute of the
      target, i.e. replacing the target's actual DOM node. hx-push-url tells
      htmx to push the fetched URL into the browser history, so we can use
      the backwards/forwards buttons to navigate these subpages.
    -->
    <nav hx-target="#main" hx-swap="outerHTML" hx-push-url="true">
      <ul>
        {% if page.number != 1 %}
          <li>
            <!--
              For each link we use hx-get to tell htmx to fetch that URL and
              swap it in. We also repeat the URL in the href attribute so the
              page works without JavaScript, and to ensure the link is
              displayed as clickable.
            -->
            <a hx-get="?page=1" href="?page=1">
              &laquo; First
            </a>
          </li>
        {% endif %}
        {% if page.has_previous %}
          <li>
            <a hx-get="?page={{ page.previous_page_number }}" href="?page={{ page.previous_page_number }}">
              {{ page.previous_page_number }}
            </a>
          </li>
        {% endif %}
        <li>
          {{ page.number }}
        </li>
        {% if page.has_next %}
          <li>
            <a hx-get="?page={{ page.next_page_number }}" href="?page={{ page.next_page_number }}">
              {{ page.next_page_number }}
            </a>
          </li>
        {% endif %}
        {% if page.number != page.paginator.num_pages %}
          <li>
            <a hx-get="?page={{ page.paginator.num_pages }}" href="?page={{ page.paginator.num_pages }}">
              &raquo; Last
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </section>
{% endblock %}